# Generated by Django 4.1.2 on 2022-12-06 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emaillist',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='emaillist',
            name='last_name',
        ),
    ]
