# Generated by Django 4.1.2 on 2022-12-06 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_emaillist_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillist',
            name='subscribed_emails',
            field=models.CharField(max_length=60),
        ),
    ]
