# Generated by Django 4.1.2 on 2022-12-06 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_emaillist_subscribed_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillist',
            name='first_name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='emaillist',
            name='last_name',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
