# Generated by Django 4.1.2 on 2022-12-08 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_newsarticle_image_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='content',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='title',
            field=models.CharField(max_length=60),
        ),
    ]
