# Generated by Django 4.1.2 on 2022-12-12 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_alter_emaillist_subscribed_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invasivereport',
            name='when_they_found_it',
            field=models.DateField(blank=True, null=True),
        ),
    ]
