# Generated by Django 4.1.2 on 2023-01-02 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_alter_donation_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillist',
            name='subscribed_email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='invasivereport',
            name='phone_number',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
