# Generated by Django 4.1.2 on 2023-01-02 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_alter_emaillist_subscribed_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillist',
            name='subscribed_email',
            field=models.EmailField(max_length=100),
        ),
    ]
