# Generated by Django 4.1.2 on 2022-11-05 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlisting',
            old_name='description',
            new_name='product_description',
        ),
    ]
