# Generated by Django 4.1.2 on 2022-11-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_bidding_alter_auctionlisting_initial_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidding',
            name='bid_amount',
            field=models.FloatField(default=0),
        ),
    ]
