# Generated by Django 4.1.2 on 2022-11-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_bidding_bid_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidding',
            name='bid_amount',
            field=models.IntegerField(),
        ),
    ]
