# Generated by Django 4.1.2 on 2022-11-07 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_bidding_bid_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='initial_price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bid', to='auctions.bidding'),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='bid_amount',
            field=models.FloatField(),
        ),
    ]
