# Generated by Django 4.1.2 on 2022-11-07 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_auctionlisting_initial_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='initial_price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price', to='auctions.bidding'),
        ),
    ]
