# Generated by Django 4.1.2 on 2022-12-06 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_emaillist_subscribed_emails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillist',
            name='subscribed_emails',
            field=models.EmailField(max_length=60),
        ),
    ]
