# Generated by Django 4.1.2 on 2022-12-08 01:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_newsarticles_newsarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
