# Generated by Django 4.1.2 on 2022-12-08 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_newsarticle_image_height_newsarticle_image_width_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsarticle',
            name='image_height',
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='image_width',
        ),
    ]
