# Generated by Django 4.1.2 on 2022-12-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_newsarticle_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvasiveReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what_they_found', models.CharField(max_length=200, null=True)),
                ('where_they_found_it', models.CharField(max_length=200, null=True)),
                ('under_water_or_floating', models.BooleanField()),
                ('did_they_collect_a_sample', models.BooleanField()),
                ('name', models.CharField(max_length=200, null=True)),
                ('phone_number', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('comments', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
