# Generated by Django 4.1.2 on 2022-12-10 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_invasivereports'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InvasiveReports',
            new_name='InvasiveReport',
        ),
    ]
