# Generated by Django 4.1.2 on 2022-12-10 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_rename_invasivereports_invasivereport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invasivereport',
            name='did_they_collect_a_sample',
        ),
        migrations.RemoveField(
            model_name='invasivereport',
            name='under_water_or_floating',
        ),
        migrations.AddField(
            model_name='invasivereport',
            name='collected_a_sample_no',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='invasivereport',
            name='collected_a_sample_yes',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='invasivereport',
            name='floating',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='invasivereport',
            name='under_water',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='invasivereport',
            name='when_they_found_it',
            field=models.DateField(null=True),
        ),
    ]
