# Generated by Django 4.1.2 on 2022-12-10 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_remove_invasivereport_did_they_collect_a_sample_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invasivereport',
            old_name='collected_a_sample_yes',
            new_name='did_you_collect_a_sample',
        ),
        migrations.RenameField(
            model_name='invasivereport',
            old_name='under_water',
            new_name='under_water_or_floating',
        ),
        migrations.RemoveField(
            model_name='invasivereport',
            name='collected_a_sample_no',
        ),
        migrations.RemoveField(
            model_name='invasivereport',
            name='floating',
        ),
    ]
