# Generated by Django 4.1.2 on 2022-12-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_alter_invasivereport_when_they_found_it'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invasivereport',
            name='when_they_found_it',
            field=models.DateField(null=True),
        ),
    ]
