# Generated by Django 4.1.2 on 2022-12-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_invasivereport_when_they_found_it'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillist',
            name='subscribed_email',
            field=models.EmailField(max_length=60, unique=True),
        ),
    ]
