# Generated by Django 4.1.2 on 2022-12-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_alter_emaillist_subscribed_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillist',
            name='subscribed_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
