# Generated by Django 4.1.2 on 2022-12-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_alter_emaillist_subscribed_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillist',
            name='subscribed_email',
            field=models.EmailField(error_messages={'unique': 'This email is already subscribed'}, max_length=100, unique=True),
        ),
    ]
