# Generated by Django 4.1.2 on 2022-12-13 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_alter_newsarticle_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_specification', models.CharField(max_length=80, null=True)),
                ('in_honor_of', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
