# Generated by Django 4.1.2 on 2023-01-02 20:12

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_alter_emaillist_subscribed_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invasivereport',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=200, null=True, region='US'),
        ),
    ]
