# Generated by Django 4.1.2 on 2023-01-02 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_alter_invasivereport_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invasivereport',
            name='phone_number',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
